# Generated by Django 5.2.1 on 2025-06-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified',
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('', 'None'), ('Open', 'Open'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, to='api.employees'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.projectmanager'),
            preserve_default=False,
        ),
    ]
